<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Tregmine Item Database</h3>
            </div>

            <?php if (hasRank("junior_admin", "senior_admin")): ?>
            <a href="#addItem" data-toggle="modal" class="btn btn-default form-control">
                <span class="glyphicon glyphicon-plus-sign"></span> Add new item
            </a>

            <div class="modal fade" id="addItem" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content modal-width-reset">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Add new item</h4>
                        </div>
                        <div class="modal-body">
                            <div class="alert alert-info">If you do not understand the image link structure - Leave it blank.<br />
                                Try and make all names as clear as possible!</div>

                            <form method="post" action="/admin/items/newitem" role="form">
                                <input type="hidden" id="itemPage" value="<?php echo $current; ?>" />
                                <div class="form-group">
                                    <label for="itemID" class="col-sm-3 control-label">Item ID</label>
                                    <div class="col-sm-9">
                                        <input type="name" class="form-control" id="itemID" name="itemID" placeholder="Item ID" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="itemData" class="col-sm-3 control-label">Item Data</label>
                                    <div class="col-sm-9">
                                        <input type="name" class="form-control" id="itemData" name="itemData" placeholder="Item Data" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="itemFullName" class="col-sm-3 control-label">Full Name</label>
                                    <div class="col-sm-9">
                                        <input type="name" class="form-control" id="itemFullName" name="itemFullName" placeholder="Item Name - Full Variation" required>
                                        <span class="help-block">Full English name of the item or block.</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="itemSignName" class="col-sm-3 control-label">Sign Name</label>
                                    <div class="col-sm-9">
                                        <input type="name" class="form-control" id="itemSignName" name="itemSignName" placeholder="Item Name - Sign Variation" maxlength="15" required>
                                        <span class="help-block">Version of the item/block name that can fit on a sign!</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-9">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" id="itemEnch" name="itemEnch"> Can be enchanted?
                                            </label>
                                            <span class="help-block">Tick for items that can be enchanted in survival!</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-9">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"> Can be sold in '/sell'
                                            </label>
                                            <span class="help-block">This value can only be modified on <a>this</a> page</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-9">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" disabled value="1"> Can be auctioned?
                                            </label>
                                            <span class="help-block">This feature has yet to be coded, so is disabled!</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="itemLink" class="col-sm-3 control-label">Image Link</label>
                                    <div class="col-sm-9">
                                        <input type="name" class="form-control" id="itemLink" name="itemLink" placeholder="Item Link">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-9">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" id="itemRound" name="itemRound" value="1"> Round image?
                                            </label>
                                            <span class="help-block">If this image is a full block, then round it.</span>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-default">Add Item</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <?php endif; ?>

            <table class="table table-striped table-hover">
                <cols>
                    <col />
                    <col style="width: 250px;" />
                </cols>
                <tr>
                    <th><a href="/items?order=id">ID</a></th>
                    <th><a href="/items?order=name">Name</a></th>
                    <th><a href="/items?order=value">Sign Version</a></th>

                    <?php if (hasRank("junior_admin", "senior_admin")): ?>
                    <th>Actions</th>
                    <?php endif; ?>
                </tr>
                <?php foreach ($items as $item): ?>
                    <?php
                        $link = $item['link'];
                        $class = "";
                        if (!file_exists("../public/img/texture/default/" . $link) || $link == null) {
                            $class = "class=\"danger\"";
                        } else if ($item['item_name'] == null || $item['item_sign'] == null) {
                            $class = "class=\"warning\"";
                        }
                    ?>
                    <tr <?php echo $class; ?>>
                        <td>
                            <?php echo $item['item_id'] . ":" . $item['item_data']; ?>
                        </td>
                        <td>
                            <?php echo $item['item_name']; ?>
                        </td>
                        <td>
                            <?php
                                if ($item['item_sign'] == null) {
                                    echo "Not Set";
                                } else {
                                    echo $item['item_sign'];
                                }
                            ?>
                        </td>

                        <?php if (hasRank("junior_admin", "senior_admin")): ?>
                        <td>
                            <a href="#modifyItem<?php echo $item['item_id'] . "-" . $item['item_data']; ?>" data-toggle="modal" class="glyphicon glyphicon-pencil black"></a>
                            <a href="/admin/items/deleteitem?id=<?php echo $item['item_id']; ?>&data=<?php echo $item['item_data']; ?>" class="glyphicon glyphicon-minus-sign black"></a>
                        </td>

                        <div class="modal fade" id="modifyItem<?php echo $item['item_id'] . "-" . $item['item_data']; ?>" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content modal-width-reset">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Modify Item: <?php echo $item['item_name'] . " (" . $item['item_id'] . ":" . $item['item_data'] . ")"; ?></h4>
                                    </div>
                                    <div class="modal-body">
                                        <form method="post" action="/admin/items/updateitem" role="form" class="form-horizontal">
                                            <input type="hidden" id="itemPage" value="<?php echo $current; ?>" />
                                            <input type="hidden" name="itemID" id="itemID" value="<?php echo $item['item_id']; ?>" />
                                            <input type="hidden" name="itemData" id="itemData" value="<?php echo $item['item_data']; ?>" />

                                            <div class="form-group">
                                                <label for="itemFullName" class="col-sm-3 control-label">Full Name</label>
                                                <div class="col-sm-9">
                                                    <input type="name" class="form-control" id="itemFullName" name="itemFullName" value="<?php echo $item['item_name']; ?>" placeholder="Item Name - Full Variation" required>
                                                    <span class="help-block">Full English name of the item or block.</span>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="itemSignName" class="col-sm-3 control-label">Sign Name</label>
                                                <div class="col-sm-9">
                                                    <input type="name" class="form-control" id="itemSignName" name="itemSignName" value="<?php echo $item['item_sign']; ?>" placeholder="Item Name - Sign Variation" maxlength="15" required>
                                                    <span class="help-block">Version of the item/block name that can fit on a sign!</span>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-3 col-sm-9">
                                                    <div class="checkbox">
                                                        <label>
                                                            <input type="checkbox" id="itemEnch" name="itemEnch" value="1" <?php echo $item["enchantable"] == "yes" ? 'checked="checked"' : ''; ?>> Can be enchanted?
                                                        </label>
                                                        <span class="help-block">Tick for items that can be enchanted in survival!</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-3 col-sm-9">
                                                    <div class="checkbox">
                                                        <label>
                                                            <input type="checkbox" disabled value="1" <?php echo $item["sellable"] == "yes" ? 'checked="checked"' : ''; ?>> Can be sold in '/sell'
                                                        </label>
                                                        <span class="help-block">This value can only be modified on <a>this</a> page</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-3 col-sm-9">
                                                    <div class="checkbox">
                                                        <label>
                                                            <input type="checkbox" disabled value="1" <?php echo $item["auctionable"] == "yes" ? 'checked="checked"' : ''; ?>> Can be auctioned?
                                                        </label>
                                                        <span class="help-block">This feature has yet to be coded, so is disabled!</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="itemLink" class="col-sm-3 control-label">Image Link</label>
                                                <div class="col-sm-9">
                                                    <input type="name" class="form-control" id="itemLink" name="itemLink" value="<?php echo $item['link']; ?>" placeholder="Item Link">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-3 col-sm-9">
                                                    <div class="checkbox">
                                                        <label>
                                                            <input type="checkbox" id="itemRound" name="itemRound" value="1" <?php echo $item["round"] == "yes" ? 'checked="checked"' : ''; ?>> Round image?
                                                        </label>
                                                        <span class="help-block">If this image is a full block, then round it.</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-default">Update</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </table>
            <div class="panel-body">
                <ul class="pagination">
                    <li <?php echo $previous; ?>><a href="/admin/items?pg=1">1</a></li>
                    <li <?php echo $previous; ?>><a <?php echo $previousLink; ?>>&laquo;</a></li>
                    <li class="active">          <a ><?php echo $current; ?></a></li>
                    <li <?php echo $next; ?>>    <a <?php echo $nextLink; ?>>&raquo;</a></li>
                    <li <?php echo $next; ?>>    <a href="/admin/items?pg=<?php echo $last; ?>"><?php echo $last; ?></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'logs_menu.phtml'; ?>

        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Table Key</h3>
            </div>
            <table class="table">
                <tr class="danger">
                    <td>Image not found</td>
                </tr>
                <tr class="warning">
                    <td>Please Review</td>
                </tr>
            </table>
        </div>
    </div>
</div>
