<form class="wide">
    <input type="hidden" id="token" value="<?php echo $token; ?>" />

    <h3 class="formHeader">Message</h3>

    <div class="field">
        <label for="channel">Channel</label>
        <div class="element">
            <input type="text" name="channel" id="channel" value="GLOBAL" />
        </div>
        <div class="end">&nbsp;</div>
    </div>

    <div class="field">
        <label for="message">Text</label>
        <div class="element">
            <input type="text" name="message" id="message" />
        </div>
        <div class="end">&nbsp;</div>
    </div>

    <div class="button">
        <button id="send" type="button">Send</button>
    </div>
</form>

<h3 class="infoHeader">Log</h3>
<table class="info">
    <cols>
        <col style="width: 100px;" />
        <col style="width: 100px;" />
        <col style="width: 100px;" />
        <col />
    </cols>
    <thead>
        <tr>
            <th>Timestamp</th>
            <th>Channel</th>
            <th>Sender</th>
            <th>Text</th>
        </tr>
    </thead>
    <tbody id="log">
    </tbody>
</table>
