<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Do you want to finsih your donation?</h3>
            </div>
            <div class="panel-body">
                As of yet, no money has been charged to your card or paypal account. If you are sure
                you want to proceed, click on the link below. Otherwise, just close this page.
            </div>
            <div class="alert alert-success">
                <a href="/index.php/donate/confirm/do?payerId=<?php echo $payerId; ?>" style="font-size: 16px; font-weight: bold;">Finish donation!</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">Donation Steps</div>
            <ul class="list-group">
                <li class="list-group-item dark_blue">Select donation amount</li>
                <li class="list-group-item dark_blue">Login at paypal</li>
                <li class="list-group-item dark_blue">Enter payment information</li>
                <li class="list-group-item blue">Confirm donation</li>
                <li class="list-group-item">Finished!</li>
            </ul>
        </div>
    </div>
</div>
