<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Thank you for donating!</h3>
            </div>
            <div class="alert alert-success">
                If you donated enough to receive a zone or a warp, please talk to an admin,
                and he or she will help you!
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">Donation Steps</div>
            <ul class="list-group">
                <li class="list-group-item dark_blue">Select donation amount</li>
                <li class="list-group-item dark_blue">Login at paypal</li>
                <li class="list-group-item dark_blue">Enter payment information</li>
                <li class="list-group-item dark_blue">Confirm donation</li>
                <li class="list-group-item blue">Finished!</li>
            </ul>
        </div>
    </div>
</div>