<div class="col col75">
    <h2>Do you want to finish your donation?</h2>

    <p>
        As of yet, no money has been charged to your card or paypal account. If you are sure
        you want to proceed, click on the link below. Otherwise, just close this page.
    </p>

    <p style="text-align: center;">
        <a href="/index.php/donate/confirm/do?payerId=<?php echo $payerId; ?>" style="font-size: 16px; font-weight: bold;">Finish donation!</a>
    </p>
</div>

<div class="col25">
    <h3 class="actionsHeader">Donation Step</h3>
    <ol class="actions">
        <li class="done">Select donation amount</li>
        <li class="done">Login at paypal</li>
        <li class="done">Enter payment information</li>
        <li class="active">Confirm donation</li>
        <li>Finished!</li>
    </ol>
</div>

<div class="col_clear">&nbsp;</div>
