<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Why would I donate?</h3>
            </div>
            <div class="panel-body">
                Tregmine is run entirely on a volunteer basis. Nobody makes any money off of Tregmine, and server
                costs are funded out of our own pockets. If you want to help us to keep the server running,
                you are welcome to make a donation.
            </div>
        </div>

        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Notice:</h3>
            </div>
            <div class="panel-body">
                It is <b>vital</b> that you join Discord if you will be donating. Remember, it is <b>your</b> responsibility to get in touch with an admin to set up your zone and / or warp. More details are available <a href="https://docs.google.com/document/d/1YZARKy2CIXNGoi0s5rokxowB_UE2cFfnsT1uDo21xQA/edit?usp=sharing">in section 2A of the tregmine policy</a>.
            </div>
        </div>

        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">What donators get.</h3>
            </div>
            <div class="panel-body">
                All donations over $5 USD will receive the following gifts as our way of saying thanks:
            </div>
            <ul class="list-group">
                <li class="list-group-item">Gold colored name in the forums and in-game to show everyone you are a donator.</li>
                <li class="list-group-item">Ability to save a home teleport location, and warp there anytime by typing /home.</li>
                <li class="list-group-item">Teleport to players who are 10,000 blocks away.</li>
                <li class="list-group-item">Prevent other players from teleporting to you.</li>
                <li class="list-group-item">One free single blessed chest (a 30,000 Treg value!) and the option to upgrade to a double-blessed chest for an additional 30,000 Tregs.</li>
                <li class="list-group-item">Permission to use client-side mods for flying or other enhanced movement. (Does not apply to Donators who are currently warned and have a grey name.)</li>
                <li class="list-group-item">Access to donator-only warps and forums.</li>
                <li class="list-group-item">Reduced wait times when warping or teleporting.</li>
                <li class="list-group-item">Option to beta test new plugins.</li>
                <li class="list-group-item">Promotions to ranks such as Builder, Guardian or Admin will only be offered to donators.</li>
                <li class="list-group-item">A zone or a warp</li>
            </ul>
            <div class="panel-body">
                Donations of higher amounts will receive the above list of gifts, plus:
            </div>
            <ul class="list-group">
                <li class="list-group-item">$10 USD or more: You get a complimentary warp <em>and</em> a zone.</li>
            </ul>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Donate using Paypal</h3>
            </div>
            <div class="panel-body">
                If you have any specific wishes regarding who should receive the gifts of your donation,
                type them in the message field.
            </div>
            <div class="panel-body">
                <form role="form" method="get" action="/donate/do">
                    <div class="form-group">
                        <label for="amount">Amount (USD)</label>
                        <input type="text" class="form-control" id="amount" name="amount" value="10" />
                    </div>
                    <div class="form-group">
                        <label for="message">Message</label>
                        <input type="text" class="form-control" id="message" name="message" value="" />
                    </div>
                    <button type="submit" class="btn btn-default">Donate</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">Donation Steps</div>
            <ul class="list-group">
                <li class="list-group-item blue">Select donation amount</li>
                <li class="list-group-item">Login at paypal</li>
                <li class="list-group-item">Enter payment information</li>
                <li class="list-group-item">Confirm donation</li>
                <li class="list-group-item">Finished!</li>
            </ul>
        </div>
    </div>
</div>
