<div class="col col75" style="background-color: #fff;">
    <h2>Thank you for donating!</h2>

    <p>
        If you donated enough to receive a zone or a warp, please talk to an admin,
        and he or she will help you!
    </p>
</div>

<div class="col25">
    <h3 class="actionsHeader">Donation Step</h3>
    <ol class="actions">
        <li class="done">Select donation amount</li>
        <li class="done">Login at paypal</li>
        <li class="done">Enter payment information</li>
        <li class="done">Confirm donation</li>
        <li class="active">Finished!</li>
    </ol>
</div>

<div class="col_clear">&nbsp;</div>
