<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                <div class="alert alert-info">
                    After creating a zone or warp for the player, please write a
                    report with the name of the zone and warp, and the donation id.
                </div>
            </div>
            <table class="table table-striped table-hover">
                <tr>
                    <th style="width: 100px;">Donation ID</th>
                    <th>Player</th>
                    <th>Amount</th>
                    <th>Timestamp</th>
                    <th>Message</th>
                    <th style="width: 75px;">Actions</th>
                </tr>
                <?php foreach ($donations as $player): ?>
                    <tr>
                        <td style="text-align: center;">
                            <?php echo $player["donation_id"]; ?>
                        </td>
                        <td>
                            <a <?php echo userCSSColor($player["player_id"]); ?>" href="/player/search?q=<?php echo $player["player_name"]; ?>"> <?php echo $player["player_name"]; ?></a>
                        </td>
                        <td><?php echo $player["donation_amount"]; ?></td>
                        <td><?php echo niceTime($player["donation_timestamp"]); ?></td>
                        <td><?php echo $player["donation_message"]; ?></td>
                        <td>
                            &raquo; <a href="/player/report?id=<?php echo $player["player_id"]; ?>&type=donate">Report</a><br />
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'logs_menu.phtml'; ?>
    </div>
</div>
