<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Federal Reserve of Tregmine Prices</h3>
            </div>
            <table class="table table-striped table-hover">
                <cols>
                    <col />
                    <col style="width: 250px;" />
                </cols>
                <tr>
                    <th>Item Information</th>
                    <th>Item Value</th>
                </tr>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td>
                            <?php echo $item['item_name'] . " (" . $item['item_id'] . ":" . $item['item_data'] . ")"; ?>
                        </td>
                        <td>
                            <?php echo $item['item_value']; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'economy_menu.phtml'; ?>
    </div>
</div>
