<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Federal Reserve of Tregmine Prices</h3>
            </div>

            <?php if (hasRank("junior_admin", "senior_admin")): ?>
            <a href="" class="btn btn-default form-control">
                <span class="glyphicon glyphicon-plus-sign"></span> Add new item
            </a>
            <?php endif; ?>

            <table class="table table-striped table-hover">
                <cols>
                    <col />
                    <col style="width: 250px;" />
                </cols>
                <tr>
                    <th>Item Information</th>
                    <th>Item Value</th>

                    <?php if (hasRank("junior_admin", "senior_admin")): ?>
                    <th>Actions</th>
                    <?php endif; ?>
                </tr>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td>
                            <?php echo $item['item_name'] . " (" . $item['item_id'] . ":" . $item['item_data'] . ")"; ?>
                        </td>
                        <td>
                            <?php echo $item['item_value']; ?>
                        </td>

                        <?php if (hasRank("junior_admin", "senior_admin")): ?>
                        <td>
                            <a class="glyphicon glyphicon-pencil black"></a>
                            <a href="/index.php/economy/deleteSell?id=<?php echo $item['item_id']; ?>&data=<?php echo $item['item_data']; ?>" class="glyphicon glyphicon-minus-sign black"></a>
                        </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'economy_menu.phtml'; ?>
    </div>
</div>
