<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $title; ?> <small>mc.tregmine.info</small></h3>
    </div>
    <div class="panel-body">
        Tregmine is a Minecraft Economy server running Bukkit (1.7.2).
        We have two individual worlds, the zone world and the anarchy world.
        If you want to build up towns and establishments or work together raiding and causing havok -
        This is the server to do it at! All our plugins are developed by our own fantastic team as well.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Recent News</h3>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">New Hompeage!</h3>
    </div>
    <div class="panel-body">
        <p>As many of you know, we have had a basic website in addition to our forum for a while.
            However, it has been acknowledged many a time that it is hard to navigate and lacks a lot of fundamental requirements in order to be as helpful as it should.
        That is why our team of coders have worked together in putting together what you are now reading this on. The layout is quite simplistic but is easy to change upon suggestions,
        It's very expandable and we will be continuing to add more pages and features as time goes by.</p>
        <p>If you happen to find any mistakes or pages we missed in the process of transferring from the old layout to this new one
            then do not hesitate but to contact an administrator via the forum or server.</p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Tregmins is back after latest attack. <small>9th September, 2013</small></h3>
    </div>
    <div class="panel-body">
        <p>Tregmine is back after a prolonged service disruption
        caused by a DDOS attack. We have taken steps to safeguard
        ourselves from similiar efforts, by deploying a DDOS
        defense service. While we're not yet sure if it'll prove
        effective, we hope that it'll make us more resilient.</p>
        <p>We do not know who perpetrated this attack, or for what
        reason. DDOS's are by definition hard to trace, and even
        though we'll make an effort, the likelihood of actually
        tracking someone is low.</p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Plugins are now open source!</h3>
    </div>
    <div class="panel-body">
        <p>Although it has been in the works for many years, it's
        finally done: The Tregmine plugins are open source, and
        available <a href="http://github.com/EmilHernvall/tregmine">on github</a>.</p>
        <p>Contributions are welcome!</p>
    </div>
</div>
