<div class="row">
    <div class="col-xs-12 col-md-8">
        <?php require_once 'index_news.phtml'; ?>

        <div class="row">
            <div class="col-xs-6 table-responsive">
                <div class="panel panel-default">
                    <table class="table table-striped table-responsive table-hover">
                        <tr>
                            <th colspan="2">Player</th>
                        </tr>
                        <?php foreach ($logins as $login): ?>
                            <tr>
                                <td rowspan="1" style="width: 20px;">
                                    <img src="/index.php/player/head?player=<?php echo $login["player_name"]; ?>&factor=4" class="img-rounded table-margin-5" />
                                </td>
                                <td>
                                    <a <?php echo userCSSColor($login["player_id"]); ?> href="/index.php/player/search?q=<?php echo $login["player_name"]; ?>">
                                        <?php echo $login["player_name"]; ?>
                                    </a><br/>
                                    <?php echo niceTime($login["login_timestamp"]); ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>

            <div class="col-xs-6 table-responsive">
                <div class="panel panel-default">
                    <table class="table table-striped table-responsive table-hover">
                        <tr>
                            <th colspan="2">New Member</th>
                            <th colspan="2">Mentor</th>
                        </tr>
                        <?php foreach ($settlers as $settler): ?>
                            <tr>
                                <td rowspan="1" style="width: 20px;">
                                    <img src="/index.php/player/head?player=<?php echo $settler["student_name"]; ?>&factor=4" class="img-rounded table-margin-5" />
                                </td>
                                <td>
                                    <a <?php echo userCSSColor($settler["student_id"]); ?> href="/index.php/player/search?q=<?php echo $settler["student_name"]; ?>">
                                        <?php echo $settler["student_name"]; ?>
                                    </a>
                                </td>
                                <td>
                                    <a <?php echo userCSSColor($settler["mentor_id"]); ?> href="/index.php/player/search?q=<?php echo $settler["mentor_name"]; ?>">
                                        <?php echo $settler["mentor_name"]; ?>
                                    </a>
                                </td>
                                <td colspan="2"><?php echo niceTime($settler["mentorlog_completedtime"]); ?></td>
                                <td rowspan="1" style="width: 20px;">
                                    <img src="/index.php/player/head?player=<?php echo $settler["mentor_name"]; ?>&factor=4" class="img-rounded table-margin-5" />
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <?php if (!array_key_exists("online", $_SESSION)): ?>
            <?php if (array_key_exists("error", $_GET)) { ?>
                <div class="panel panel-danger">
            <?php } else { ?>
                <div class="panel panel-default">
            <?php } ?>
                <div class="panel-heading"><h3 class="panel-title">Login</h3></div>
                <div class="panel-body">
                    <form method="post" action="/index.php/login" role="form">
                        <?php if (array_key_exists("error", $_GET)): ?>
                            <div class="alert alert-danger">
                                Invalid username or password!
                            </div>
                        <?php endif; ?>

                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" name="username" />
                        </div>
                        <div class="form-group">
                            <label for="pass">Password</label>
                            <input type="password" class="form-control" id="pass" name="pass" />
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="remember" name="remember" value="1"> Remember me?
                            </label>
                        </div>
                        <button type="submit" class="btn btn-default">Login</button>
                    </form>
                </div>
            </div>
        <?php else: ?>
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Player Information</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12 col-md-8">
                            <div <?php echo userCSSColor($_SESSION["id"]); ?> style="font-size: 14px; font-weight: bold;">
                                <?php
                                    echo $_SESSION["name"] . "<br />";
                                    echo ucwords(str_replace("_", " ", $_SESSION["rank"]));
                                ?>
                            </div>
                        </div>

                        <div class="col-xs-6 col-md-4">
                            <img src="/index.php/player/skin?player=<?php echo $_SESSION["name"]; ?>&factor=4" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Player Quick search</h3></div>
                <div class="panel-body">
                    <form role="form" method="get" action="/index.php/player/search">
                        <div class="form-group">
                            <label for="player_search">Username</label>
                            <input type="text" class="form-control" id="player_search" name="q" />
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Zone Quick search</h3></div>
                <div class="panel-body">
                    <form role="form" method="get" action="/index.php/zone/search">
                        <div class="form-group">
                            <label for="zone_search">Zone</label>
                            <input type="text" class="form-control" id="zone_search" name="q" />
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>
                </div>
            </div>
        <?php endif; ?>
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Todays Stats</h3></div>
            <div class="panel-body">
                <div id="hour_chart" style="width: 100%; height: 100px;"></div>
                <div id="row">
                    <div class="col-xs-12 col-md-8 text-right">
                        Logins <br />
                        Unique Players <br />
                        Max Online
                    </div>

                    <div class="col-xs-6 col-md-4">
                        <span title="Trend: <?php echo $loginsTrend; ?>"><?php echo $loginsCount; ?></span> <br />
                        <span title="Trend: <?php echo $uniqueTrend; ?>"><?php echo $uniqueCount; ?></span> <br />
                        <?php echo $maxPlayers; ?>
                    </div>
                </div>
                <div class="text-right"><a href="/index.php/stats">Last 30 days</a></div>
            </div>
        </div>
        <?php if (count($players) > 0): ?>
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Players Online</h3></div>
            <table class="table table-striped table-responsive table-hover">
                <?php
                    $hiddenCount = 0;
                    foreach($players as $player):
                        if ($player["hidden"] && !hasRank("senior_admin", "junior_admin")) {
                            $hiddenCount++;
                            continue;
                        }
                ?>
                <tr>
                    <td><img src="/index.php/player/head?player=<?php echo $login["player_name"]; ?>&factor=4" class="img-rounded image-right table-margin-5" /></td>
                    <td>
                        <a <?php echo userCSSColor($player["id"]); ?> href="/index.php/player/search?q=<?php echo $player["name"]; ?>">
                            <?php echo $player["name"]; ?>
                        </a>
                        <?php if (hasRank("guardian", "builder", "coder", "junior_admin", "senior_admin")): ?>
                            [<a href="#" onclick="kickPlayer(<?php echo $player["id"]; ?>)">Kick</a>]
                        <?php endif; ?>
                        <br />
                        <?php
                        $time = $player["playtime"];
                        $min = $time/60;
                        $sec = $time % 60;
                        printf("Time online: %d:%02d", $min, $sec);
                        ?>
                    </td>
                </tr>
                <?php endforeach; ?>
                <?php if ($hiddenCount > 0): ?>
                    <td colspan="2" style="font-style: italic;"><?php printf("%d hidden players", $hiddenCount); ?></td>
                <?php endif; ?>
            </table>
        </div>
        <?php endif; ?>
    </div>
</div>