<div class="col75 col white">
    <p style="font-family: Georgia; font-size: 16px; font-style: italic;">
        Tregmine is a Minecraft server running Bukkit. We
        have a couple of hundred active members, and we develop
        our own plugins. You are welcome to join us at:
    </p>

    <p class="emp">mc.tregmine.info</p>

    <?php
    /* obviously it's not optimal to have the news hard coded
     * in the source, but it's better than nothing. Let's fix
     * that if we get around to it later.
     */ ?>

    <h2>Recent News</h2>

    <h3>New homepage</h3>

    <p>
        For the first time, we actually have a homepage, beyond
        the forums. It's integrated directly with minecraft, and
        will serve as an information source and tool for players
        and staff. All of our players can login to this page by
        setting a password within minecraft using the /password
        command. This is currently the only way to get access.
    </p>

    <h3>Plugins are now open source</h3>

    <p>
        Although it has been in the works for many years, it's
        finally done: The Tregmine plugins are open source, and
        available <a href="http://github.com/EmilHernvall/tregmine">on github</a>.
    </p>

    <p>
        Contributions are welcome!
    </p>
</div>
