<!--<div class="col25">
    <?php require_once 'player_menu.phtml'; ?>
</div>-->

<table class="info">
    <tr>
        <th colspan="9" class="infoHeader">Inventory</th>
    </tr>
    <?php for ($x = 0; $x < 4; $x++): ?>
    <tr>
        <?php for ($y = 0; $y < 9; $y++): ?>
            <td style="width: 11%; height: 75px; border: 1px solid #000; text-align: center; font-size: 10px;">
                <?php
                if (array_key_exists($x*9+$y, $slots)) {
                    $slot = $slots[$x*9+$y];
                    $item = $slot["item_material"];
                    if (file_exists("../public/img/blocks_large/" . $item . ".png")) {
                        echo '<div><img src="/img/blocks_large/' . $item . '.png" width="50" height="50" /></div>';
                    } else {
                        echo '<div style="height: 50px;">' . 
                            implode(" ", array_map("ucfirst", array_map("strtolower", explode("_", $items[$item])))) . '</div>';
                    }
                    echo '<div>' . $slot["item_count"] . '</div>';
                } else {
                    echo "&nbsp;";
                }
                ?>
            </td>
        <?php endfor; ?>
    </tr>
    <?php endfor; ?>
</table>

<div class="col50">
    <h3 class="infoHeader">Access Log</h3>
    <table class="info">
        <tr>
            <th>Player</th>
            <th style="width: 200px;">Timestamp</th>
        </tr>
        <?php foreach ($accessLog as $access): ?>
        <tr>
            <td>
                <a href="/index.php/player/search?q=<?php echo $access["player_name"]; ?>" <?php echo userCSSColor($access["player_id"]); ?>><?php echo $access["player_name"]; ?></a>
            </td>
            <td><?php echo niceTime($access["accesslog_timestamp"]); ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<div class="col50">
    <h3 class="infoHeader">Change Log</h3>
    <table class="info">
        <cols>
            <col style="width: 50px;" />
            <col />
            <col />
            <col />
            <col style="width: 150px;" />
        </cols>
        <tr>
            <th>&nbsp;</th>
            <th>Item</th>
            <th>Amount</th>
            <th>Player</th>
            <th>Timestamp</th>
        </tr>
        <?php foreach ($changeLog as $change): ?>
        <tr style="background-color: <?php echo $change["changelog_type"] == "add" ? "#cfc" : "#fcc"; ?>;">
            <td style="width: 50px;">
                <?php
                $item = $change["changelog_material"];
                if (file_exists("../public/img/blocks/" . $item . ".png")) {
                    echo '<img src="/img/blocks/' . $item . '.png" />';
                }
                ?>
            </td>
            <td>
                <?php
                echo implode(" ", array_map("ucfirst", array_map("strtolower", explode("_", $items[$item]))));
                if ($change["changelog_data"] != 0) {
                    echo ":" . $change["changelog_data"];
                }
                ?>
            </td>
            <td><?php echo $change["changelog_amount"]; ?></td>
            <td>
                <a href="/index.php/player/search?q=<?php echo $change["player_name"]; ?>" <?php echo userCSSColor($change["player_id"]); ?>><?php echo $change["player_name"]; ?></a>
            </td>
            <td><?php echo niceTime($change["changelog_timestamp"]); ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<div class="col_clear">&nbsp;</div>
