<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Federal Reserve of Tregmine Prices</h3>
            </div>

            <?php if (hasRank("junior_admin", "senior_admin")): ?>
            <a href="#modifyItem" data-toggle="modal" class="btn btn-default form-control">
                <span class="glyphicon glyphicon-plus-sign"></span> Add new item
            </a>

            <div class="modal fade" id="modifyItem" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content modal-width-reset">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Add new sellable item</h4>
                        </div>
                        <div class="modal-body">
                            <div class="alert alert-info">You only need to specify either the 'Item Name' OR the 'Item ID & Item Data'.<br />
                            You also need to specify the price either way.</div>

                            <form method="post" action="/index.php/items/newsell" role="form">
                                <div class="form-group">
                                    <label for="itemName_search">Item Name</label>
                                    <input type="name" class="form-control" name="itemName_search" id="itemName_search" placeholder="Item Name">
                                    <span class="help-block">Allow the auto complete to select the correct name from the database.
                                        If you can't find the correct name - then use the ID/Data method.</span>
                                </div>
                                <div class="form-group">
                                    <label for="itemID">Item ID</label>
                                    <input type="name" class="form-control" name="itemID" id="itemID" placeholder="Item ID">
                                </div>
                                <div class="form-group">
                                    <label for="itemData">Item Data</label>
                                    <input type="name" class="form-control" name="itemData" id="itemData" placeholder="Item Data" value="0">
                                    <span class="help-block">Putting the data at 0 will mean all items with this ID.
                                        Change the data for accurate items based on their data.</span>
                                </div>
                                <div class="form-group">
                                    <label for="itemPrice">Price</label>
                                    <input type="name" class="form-control" name="itemPrice" id="itemPrice" placeholder="Item Price">
                                </div>
                                <button type="submit" class="btn btn-default">Add</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <?php endif; ?>

            <table class="table table-striped table-hover">
                <cols>
                    <col />
                    <col style="width: 250px;" />
                </cols>
                <tr>
                    <th>Item Information</th>
                    <th>Item Value</th>

                    <?php if (hasRank("junior_admin", "senior_admin")): ?>
                    <th>Actions</th>
                    <?php endif; ?>
                </tr>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td>
                            <?php echo $item['item_name'] . " (" . $item['item_id'] . ":" . $item['item_data'] . ")"; ?>
                        </td>
                        <td>
                            <?php echo $item['item_value']; ?>
                        </td>

                        <?php if (hasRank("junior_admin", "senior_admin")): ?>
                        <td>
                            <a href="#modifyItem" data-toggle="modal" class="glyphicon glyphicon-pencil black"></a>
                            <a href="/index.php/items/deletesell?id=<?php echo $item['item_id']; ?>&data=<?php echo $item['item_data']; ?>" class="glyphicon glyphicon-minus-sign black"></a>
                        </td>

                        <div class="modal fade" id="modifyItem" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content modal-width-reset">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Modify Item: <?php echo $item['item_name'] . " (" . $item['item_id'] . ":" . $item['item_data'] . ")"; ?></h4>
                                    </div>
                                    <div class="modal-body">
                                        <form method="post" action="/index.php/items/updatesell" role="form">
                                            <div class="form-group">
                                                <input type="hidden" name="itemID" id="itemID" value="<?php echo $item['item_id']; ?>" />
                                                <input type="hidden" name="itemData" id="itemData" value="<?php echo $item['item_data']; ?>" />

                                                <label for="newPrice">Price</label>
                                                <input type="name" class="form-control" name="newPrice" id="newPrice" placeholder="Price" value="<?php echo $item['item_value']; ?>">
                                            </div>
                                            <button type="submit" class="btn btn-default">Update</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'economy_menu.phtml'; ?>
    </div>
</div>
