<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Tregmine</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/jquery-ui.css" />
    <?php foreach ($styles as $style): ?>
    <link rel="stylesheet" href="<?php echo $style; ?>" />
    <?php endforeach; ?>
    <script src="/js/jquery-1.9.1.js"></script>
    <script src="/js/jquery-ui.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <?php foreach ($scripts as $script): ?>
    <script type="text/javascript" src="<?php echo $script; ?>"></script>
    <?php endforeach; ?>
</head>
<body>
    <div id="layout_wrapper">
        <h1 id="banner"><span>Tregmine</span></h1>

        <?php if (array_key_exists("online", $_SESSION)): ?>
        <ul id="menu">
            <li><a href="/index.php/start">Start</a></li>
            <li><a href="/index.php/staff">Staff</a></li>
            <?php if ($_SESSION["rank"] == "senior_admin"): ?>
            <li><a href="/index.php/guardians">Guardians</a></li>
            <?php endif; ?>
            <?php if ($_SESSION["rank"] == "senior_admin" || $_SESSION["rank"] == "junior_admin"): ?>
            <li><a href="/index.php/chatlog">Chat Logs</a></li>
            <li><a href="/index.php/zone/search">Zones</a></li>
            <?php endif; ?>
            <li><a href="/index.php/orelog">Ore Logs</a></li>
            <li><a href="/index.php/reports">Reports</a></li>
            <li style="float: right"><a href="/index.php/logout">Logout</a></li>
            <li style="float: right">Logged in as: <a href="/index.php/player/search?q=<?php echo $_SESSION["name"]; ?>"><?php echo $_SESSION["name"] ?></a>&nbsp;</li>
        </ul>
        <?php endif; ?>

        <h2 class="info"><?php echo $title; ?></h2>

        <?php
        $template = '../templates/' . $page;
        if (file_exists($template)) {
            include '../templates/' . $template;
        } else {
            echo $page . " not found.";
        }
        ?>
    </div>
</body>
</html>
