<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Core website covering the backend of Tregmines Minecraft Server">
    <meta name="author" content="Tregmine Development Team">
    <title>Tregmine</title>

    <link rel="stylesheet" href="/css/bootstrap.css" />
    <link rel="stylesheet" href="/css/colors.css" />
    <link rel="stylesheet" href="/css/custom.css" />

    <?php foreach ($styles as $style): ?>
    <link rel="stylesheet" href="<?php echo $style; ?>" />
    <?php endforeach; ?>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <?php foreach ($scripts as $script): ?>
    <script type="text/javascript" src="<?php echo $script; ?>"></script>
    <?php endforeach; ?>
</head>
<body>

<div class="container">
    <div class="header">
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/index.php/start">Tregmine</a>
            </div>

            <div class="collapse navbar-collapse" id="nav-1">
                <?php if (array_key_exists("online", $_SESSION)): ?>
                    <ul class="nav navbar-nav">
                        <li><a href="/index.php/start">Start</a></li>
                        <li><a href="/index.php/stats">Stats</a></li>
                        <li><a href="/index.php/staff">Staff</a></li>
                        <li><a href="http://discourse.tregmine.info/">Forum</a></li>
                        <li><a href="/index.php/donate">Donate</a></li>
                        <li><a href="/index.php/zone/search">Zones</a></li>
                        <?php if (hasRank("donator", "coder", "guardian", "builder", "junior_admin", "senior_admin")): ?>
                            <li><a href="/index.php/chat">Chat</a></li>
                        <?php endif; ?>
                        <?php if (hasRank("guardian", "coder", "builder", "junior_admin", "senior_admin")): ?>
                            <li><a href="/index.php/logs">Logs</a></li>
                        <?php endif; ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/index.php/logout">Sign out</a></li>
                        <p class="navbar-text">Signed in as <a href="/index.php/player/search?q=<?php echo $_SESSION["name"]; ?>"><?php echo $_SESSION["name"] ?></a>&nbsp;</p>
                    </ul>
                <?php else: ?>
                    <ul class="nav navbar-nav">
                        <li><a href="/index.php/start">Start</a></li>
                        <li><a href="/index.php/stats">Stats</a></li>
                        <li><a href="http://discourse.tregmine.info/">Forum</a></li>
                    </ul>
                <?php endif; ?>
            </div>
        </nav>
    </div>

    <div class="jumbotron"></div>

    <?php
        $template = '../templates/' . $page;

        if (file_exists($template)) {
            include '../templates/' . $template;
        } else {
            echo $page . " not found.";
        }
    ?>
</div>

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-43769503-1', 'tregmine.info');
ga('send', 'pageview');

</script>

<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="/js/bootstrap.js"></script>
</body>
</html>
