<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Staff</h3>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="/logs">Logs Overview</a></li>
        <li class="list-group-item"><a href="/staff/todo">To-Do List</a></li>
        <?php if (hasRank("senior_admin", "junior_admin")): ?>
            <li class="list-group-item"><a href="/chatlog">Chat Logs</a></li>
            <li class="list-group-item"><a href="/donations">Donations</a></li>
            <li class="list-group-item"><a href="/player/transfer">Player Transfer</a></li>
        <?php endif; ?>

        <?php if (hasRank("guardian", "coder", "builder", "junior_admin", "senior_admin")): ?>
            <li class="list-group-item"><a href="/orelog">Ore Logs</a></li>
            <li class="list-group-item"><a href="/reports">Reports</a></li>
            <li class="list-group-item"><a href="/mentorlog">Mentor Log</a></li>
        <?php endif; ?>

        <?php if (hasRank("senior_admin")): ?>
            <li class="list-group-item"><a href="/admin/items">Item Database</a></li>
        <?php endif; ?>
    </ul>
</div>