<div class="col-xs-12 col-md-9">
	<div class="panel panel-danger">
	    <div class="panel-heading">
	        <h3 class="panel-title">Tregmine is down</h3>
	    </div>
	    <div class="panel-body">
	        <p>Oh noes! It looks like Tregmine is down.. Check back in 15 minutes.</p>
	    </div>
	</div>
</div>
<div class="row">
    <div class="col-xs-12 col-md-3">
            <div class="panel panel-warning">
                <div class="panel-heading"><h3 class="panel-title">What do I do now?</h3></div>
                <div class="panel-body">
                	You can head onto <a href="https://discord.gg/0uSbLbQIFDRpUYvW">our Discord</a> to get more information on the reason and length of the maintenance.
                </div>
            </div>
    </div>
</div>
