<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Mentor Log</h3>
            </div>
            <table class="table table-striped table-hover">
                <tr>
                    <th>Student</th>
                    <th>Status</th>
                    <th>Time</th>
                    <th>Channel</th>
                </tr>
                <?php foreach ($sessions as $session): ?>
                    <tr>
                        <td>
                            <div>Student: <a <?php echo userCSSColor($session["student_id"]); ?>" href="/session/search?q=<?php echo $session["student_name"]; ?>"> <?php echo $session["student_name"]; ?></a></div>
                            <div>Mentor: <a <?php echo userCSSColor($session["mentor_id"]); ?>" href="/session/search?q=<?php echo $session["mentor_name"]; ?>"> <?php echo $session["mentor_name"]; ?></a></div>
                        </td>
                        <td><?php echo ucfirst($session["mentorlog_status"]); ?></td>
                        <td>
                            <div>Started: <?php echo niceTime($session["mentorlog_startedtime"]); ?></div>
                            <div>Ended: <?php
                                if ($session["mentorlog_status"] == "completed") {
                                    echo niceTime($session["mentorlog_completedtime"]);
                                }
                                else if ($session["mentorlog_status"] == "cancelled") {
                                    echo niceTime($session["mentorlog_cancelledtime"]);
                                }
                                ?></div>
                            <div>Duration: <?php
                                $dur = 0;
                                if ($session["mentorlog_status"] == "completed") {
                                    $dur = $session["mentorlog_completedtime"] - $session["mentorlog_startedtime"];
                                }
                                else if ($session["mentorlog_status"] == "cancelled") {
                                    $dur = $session["mentorlog_cancelledtime"] - $session["mentorlog_startedtime"];
                                }
                                $min = $dur / 60;
                                $sec = $dur % 60;
                                printf("%02d:%02d", $min, $sec);
                                ?></div>
                            <?php if ($session["mentorlog_resumed"]): ?>
                                <div>
                                    Resumed <?php echo $session["mentorlog_resumed"]; ?> times
                                </div>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if ($session["mentorlog_channel"]): ?>
                                <a href="/chatlog?channel=<?php echo $session["mentorlog_channel"]; ?>"><?php echo $session["mentorlog_channel"]; ?></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'logs_menu.phtml'; ?>
    </div>
</div>
