<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Ore Log</h3>
            </div>
            <div class="panel-body">
                <form method="get" action="/orelog" role="form">
                    <div class="form-group">
                        <label for="start">Start Date</label>
                        <input type="text" class="form-control" id="start" name="start" value="<?php echo $start; ?>" />
                    </div>
                    <div class="form-group">
                        <label for="end">End Date</label>
                        <input type="text" class="form-control" id="end" name="end" value="<?php echo $end; ?>" />
                    </div>
                    <button type="submit" class="btn btn-default">Filter</button>
                </form>
            </div>
        </div>

        <div class="panel panel-warning table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Logs</h3>
            </div>
            <table class="table table-striped table-hover">
                <tr>
                    <th>Player</th>
                    <th>World</th>
                    <th>Ore</th>
                    <th>Count</th>
                </tr>
                <?php foreach ($log as $player): ?>
                    <tr>
                        <td>
                            <a <?php echo userCSSColor($player["player_id"]); ?>" href="/player/orelog?id=<?php echo $player["player_id"]; ?>"> <?php echo $player["player_name"]; ?></a>
                        </td>
                        <td><?php echo $player["orelog_world"]; ?></td>
                        <td><?php echo $player["item_name"]; ?></td>
                        <td><?php echo $player["c"]; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'logs_menu.phtml'; ?>
    </div>
</div>