<div class="col75">
    <form method="post" action="/index.php/player/report/save?id=<?php echo $player["player_id"]; ?>" class="wide">

        <h3 class="formHeader">New Report</h3>

        <div class="field">
            <label for="action">Action</label>
            <div class="element">
                <select name="action" id="action">
                    <option value="comment">Comment</option>
                    <?php if (hasRank("junior_admin", "senior_admin")): ?>
                    <option value="softwarn">Softwarn</option>
                    <option value="hardwarn">Hardwarn</option>
                    <option value="ban">Ban</option>
                    <?php endif; ?>
                </select>
            </div>
            <div class="end">&nbsp;</div>
        </div>

        <?php if (hasRank("junior_admin", "senior_admin")): ?>
        <div class="field">
            <label for="duration">Duration</label>
            <div class="element">
                <input type="text" id="duration" name="duration" />
            </div>
            <div class="end">&nbsp;</div>
        </div>
        <?php endif; ?>

        <div class="field">
            <label for="text">Message</label>
            <div class="element">
                <textarea id="text" name="text"></textarea>
            </div>
            <div class="end">&nbsp;</div>
        </div>

        <div class="button">
            <button type="submit">Submit</button>
        </div>

    </form>

    <p>
        Warnings, kicks and ban messages will be visible for the player in question, and should be written in
        a way that doesn't contain sensitive information. Comments are staff only, and can be used for secret
        information and opinions.
    </p>
</div>

<div class="col25">
    <?php require_once 'player_menu.phtml'; ?>
</div>

<div class="col_clear">&nbsp;</div>

<h3 class="infoHeader">History</h3>
<table style="width: 100%;" class="info">
    <cols>
        <col />
        <col style="width: 75px;" />
        <col style="width: 125px;" />
        <col style="width: 125px;" />
        <col style="width: 125px;" />
    </cols>

    <tr>
        <th>Issuer</th>
        <th>Action</th>
        <th>Timestamp</th>
        <th>Valid Until</th>
        <th>Action</th>
    </tr>
    <?php foreach ($reports as $report): ?>
        <tr>
            <td style="font-style: italic;"><?php echo $report["player_name"]; ?></td>
            <td style="font-style: italic;"><?php echo ucfirst($report["report_action"]); ?></td>
            <td style="font-style: italic;"><?php echo date("Y-m-d H:i:s", $report["report_timestamp"]); ?></td>
            <td style="font-style: italic;">
                <?php
                if ($report["report_validuntil"]) {
                    echo date("Y-m-d H:i:s", $report["report_validuntil"]);
                } else {
                    echo "N/A";
                }
                ?>
            </td>
            <td style="font-style: italic;">
                <?php
                $type = $report["report_action"] == "ban" ||
                        $report["report_action"] == "softwarn" ||
                        $report["report_action"] == "hardwarn";
                $valid = $report["report_validuntil"] > time();
                if ($type && hasRank("junior_admin", "senior_admin") && $valid): ?>
                    <a href="/index.php/player/report/save?do=cancel&reportid=<?php echo $report["report_id"]; ?>" onclick="return confirm('Are you sure?');">Cancel</a>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 10px; border-bottom: 1px dotted #fff;" colspan="5">
                <?php echo nl2br($report["report_message"]); ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
