
<div class="row">
    <div class="col-md-8">
    <?php if(isset($_SESSION['message'])){ if($_SESSION['message'] == "sendsuccess"){?>
    <div class="panel panel-success table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Your message has been sent successfully.</h3>
            </div>
        </div>
    <?php }elseif($_SESSION['message'] == "delfail"){?>
    <div class="panel panel-success table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Your message could not be deleted, check the ID and try again.</h3>
            </div>
        </div>
    <?php }
    $_SESSION['message'] = "";
    }?>
        <div class="panel panel-primary table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $settings["msgtype"]; ?> Messages</h3>
            </div>
            <table class="table table-striped table-hover">
                <tr>
                    <th>Sender</th>
                    <th>Receiver</th>
                    <th>Message</th>
                    <th>ID</th>
                </tr>
                <?php
                foreach ($mail as $row):
                    ?>
                    <tr>
                        <td><?php echo $row["sender_name"]; ?></td>
                        <td><?php echo $row["receiver_name"]; ?></td>
                        <td><?php echo $row["message"]; ?></td>
                        <td><?php echo $row["mail_id"];?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4 table-responsive">
        <div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">QuickBar</h3>
    </div>
    <ul class="list-group">
    	<li class="list-group-item"><a href="/player/mail/send">Send Mail</a></li>
    	<li class="list-group-item"><a href="/player/mail?type=all">All Mail</a></li>
        <li class="list-group-item"><a href="/player/mail?type=sent">Sent Mail</a></li>
        <li class="list-group-item"><a href="/player/mail?type=received">Received Mail</a></li>
        <li class="list-group-item"><a href="/player/mail?type=deleted">Deleted Mail</a></li>
        
    </ul>
    
</div>
<?php
        if($settings["deletable"]){
        	?>
        	<div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Delete Mail</h3></div>
                <div class="panel-body">
                    <form role="form" method="get" action="/player/mail/delete">
                        <div class="form-group">
                            <label for="mail_id">Mail ID</label>
                            <input type="text" class="form-control" id="mail_id" name="id" />
                        </div>
                        <button type="submit" class="btn btn-default">Delete</button>
                    </form>
                </div>
            </div>
        	<?php
        }
        ?>
    </div>
</div>
