<div class="panel panel-danger">
    <div class="panel-body">
        <form role="form" method="post" action="/player/transfer/do">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Old Account" id="old_player" name="old_player" />
                <br>
                <input type="text" class="form-control" placeholder="New Account" id="new_player" name="new_player" />
            </div>
            <button type="submit" class="btn btn-default">Transfer!</button>
        </form>
    </div>
</div>