<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">New Report</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="/index.php/player/report/save?id=<?php echo $player["player_id"]; ?>" role="form">
                    <div class="form-group">
                        <label for="action">Action</label>
                        <select name="action" id="action" class="form-control">
                            <option value="comment">Comment</option>
                            <?php if (hasRank("junior_admin", "senior_admin")): ?>
                                <option value="softwarn">Softwarn</option>
                                <option value="hardwarn">Hardwarn</option>
                                <option value="ban">Ban</option>
                            <?php endif; ?>
                        </select>
                    </div>

                    <?php if (hasRank("junior_admin", "senior_admin")): ?>
                    <div class="form-group">
                        <label for="duration">Duration</label>
                        <input type="text" class="form-control" id="duration" name="duration" />
                    </div>
                    <?php endif; ?>

                    <div class="form-group">
                        <label for="text">Message</label>
                        <textarea class="form-control" rows="3" id="text" name="text"></textarea>
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>

        <div class="panel panel-default table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">History</h3>
            </div>
            <table class="table table-striped table-hover">
                <cols>
                    <col />
                    <col style="width: 75px;" />
                    <col style="width: 125px;" />
                    <col style="width: 125px;" />
                    <col style="width: 125px;" />
                </cols>

                <tr>
                    <th>Issuer</th>
                    <th>Action</th>
                    <th>Timestamp</th>
                    <th>Valid Until</th>
                    <th>Action</th>
                </tr>
                <?php foreach ($reports as $report): ?>
                    <tr>
                        <td style="font-style: italic;"><?php echo $report["player_name"]; ?></td>
                        <td style="font-style: italic;"><?php echo ucfirst($report["report_action"]); ?></td>
                        <td style="font-style: italic;"><?php echo date("Y-m-d H:i:s", $report["report_timestamp"]); ?></td>
                        <td style="font-style: italic;">
                            <?php
                            if ($report["report_validuntil"]) {
                                echo date("Y-m-d H:i:s", $report["report_validuntil"]);
                            } else {
                                echo "N/A";
                            }
                            ?>
                        </td>
                        <td style="font-style: italic;">
                            <?php
                            $type = $report["report_action"] == "ban" ||
                                $report["report_action"] == "softwarn" ||
                                $report["report_action"] == "hardwarn";
                            $valid = $report["report_validuntil"] > time();
                            if ($type && hasRank("junior_admin", "senior_admin") && $valid): ?>
                                <a href="/index.php/player/report/save?do=cancel&reportid=<?php echo $report["report_id"]; ?>" onclick="return confirm('Are you sure?');">Cancel</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px dotted #fff;" colspan="5">
                            <?php echo nl2br($report["report_message"]); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'player_menu.phtml'; ?>
    </div>
</div>