    <h3 class="actionsHeader">Actions</h3>
    <ul class="actions">
        <li><a href="/index.php/player/report?id=<?php echo $player["player_id"]; ?>">Reports</a></li>
        <li><a href="/index.php/player/stats?id=<?php echo $player["player_id"]; ?>">Stats</a></li>
        <?php if (array_key_exists("senioradmin", $_SESSION)): ?>
        <li><a href="/index.php/player/perm?id=<?php echo $player["player_id"]; ?>">Permissions</a></li>
        <?php endif; ?>
        <li><a href="/index.php/player/zones?id=<?php echo $player["player_id"]; ?>">Zones and Lots</a></li>
    </ul>
