<div class="row">
    <div class="col-md-8">
      <?php if($keywordRemoved == true){?>
      <div class="alert alert-success">

			<div class="panel-heading">
				<h3 class="panel-title">Keyword Removed.<small></small></h3>
			</div>
			<div class="panel-body">
        <?php echo "The keyword for ".$player['player_name']." has been removed."; ?>
			</div>
			</div>
      <?php } ?>
        <div class="panel panel-primary table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Properties</h3>
            </div>
            <table class="table table-striped table-hover">
                <?php foreach ($psettings as $key => $value): ?>
                    <tr>
                        <td class="text-right"><?php echo $key; ?></td>
                        <td><?php echo $value; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

        <form method="post" action="/player/perm/save?id=<?php echo $player["player_id"]; ?>" role="form">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Flags</h3>
                </div>
                <div class="panel-body">
                    <?php foreach ($flags as $key => $flag):
                        if (!$flag["choice"]) continue;
                        if(isset($flag["rank"])){
                        	if($_SESSION["rank"] != $flag["rank"]){ continue ; }
                        }
                        $selected = ($player["player_flags"] & (1 << $key)) != 0; ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="flags_<?php echo $key; ?>" name="flags[<?php echo $key; ?>]" value="1" <?php if ($selected) echo 'checked="checked"'; ?>> <?php echo $flag["name"]; ?>
                            </label>
                        </div>
                    <?php endforeach; ?>

                </div>
            </div>

            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title">Player Information: "<?php echo $player["player_name"]; ?>"</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="action">Rank</label>
                        <select name="rank" id="rank" class="form-control">
                            <?php foreach ($permissionList as $key => $rank): ?>
                                <?php if ($player["player_rank"] == $key): ?>
                                    <option class="<?php echo $rank["color"]; ?>" selected="selected" value="<?php echo $key; ?>"><?php echo $rank["name"]; ?></option>
                                <?php else: ?>
                                    <option class="<?php echo $rank["color"]; ?>" value="<?php echo $key; ?>"><?php echo $rank["name"]; ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <?php if ($player["player_rank"] == "guardian"): ?>
                    <div class="form-group">
                    <?php else: ?>
                    <div class="form-group hidden">
                    <?php endif; ?>
                        <label for="guardian">Guardian Rank</label>
                        <select name="guardian" id="guardian" class="form-control">
                            <option value="">Auto Assign</option>
                            <?php for ($i = 1; $i <= $maxRank+1; $i++): ?>
                                <?php if (array_key_exists($i, $guardians)):
                                    $guardian = $guardians[$i]; ?>
                                    <?php if ($guardian["player_id"] == $player["player_id"]): ?>
                                    <option selected="selected" value="<?php echo $i; ?>"><?php echo $i; ?> - <?php echo $guardian["player_name"]; ?></option>
                                <?php else: ?>
                                    <option disabled="disabled" value="<?php echo $i; ?>"><?php echo $i; ?> - <?php echo $guardian["player_name"]; ?></option>
                                <?php endif; ?>
                                <?php else: ?>
                                    <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                <?php endif; ?>
                            <?php endfor; ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="quitmsg">Quit Message</label>
                        <input type="text" class="form-control" id="quitmsg" name="quitmsg" value="<?php echo array_key_exists("quitmessage", $psettings) ? $psettings["quitmessage"] : ""; ?>" />
                    </div>

                    <div class="form-group">
                        <label for="email">E-Mail</label>
                        <input type="text" class="form-control" id="email" name="email" value="<?php echo $player["player_email"] ? $player["player_email"] : ""; ?>" />
                    </div>

                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="text" class="form-control" id="password" name="password" />
                    </div>
                    <div class="alert alert-info">
                        The password will only be changed if you enter something in this box.
                    </div>

                    <button type="submit" class="btn btn-default">Save Changes</button>
                </div>
            </div>
        </form>

    </div>
    <div class="col-md-4">
        <?php require_once 'player_menu.phtml'; ?>
    </div>
</div>
