<div class="panel panel-primary">
    <div class="panel-body">
        <form role="form" method="post" action="/player/mail/send/done">
            <div class="form-group">
                <label for="player_search">To:</label>
                <input type="text" class="form-control" id="player_search" name="toPlayer" />
                <label for="player_search">Message:</label>
                <input type="text" class="form-control" id="player_search" name="message" />
            </div>
            <button type="submit" class="btn btn-default">Send</button>
        </form>
    </div>
</div>