<div class="panel panel-default">
    <div class="panel-body">
        <form role="form" method="get" action="/index.php/player/search">
            <div class="form-group">
                <label for="player_search">User</label>
                <input type="text" class="form-control" id="player_search" name="q" value="<?php echo htmlspecialchars($q); ?>" />
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>
    </div>
</div>

<?php if ($q): ?>
<div class="panel panel-default table-responsive">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo count($hits); ?> results for "<?php echo htmlspecialchars($q); ?>"</h3>
    </div>
    <?php if ($hits): ?>
        <table class="table table-striped table-hover">
            <cols>
                <?php if (hasRank("senior_admin", "junior_admin")): ?>
                    <col style="width: 50px;" />
                <?php endif; ?>
                <col />
                <col style="width: 200px;" />
                <?php if (hasRank("senior_admin", "junior_admin")): ?>
                    <col style="width: 150px;" />
                <?php endif; ?>
                <col style="width: 200px;" />
            </cols>
            <tr>
                <?php if (hasRank("senior_admin", "junior_admin")): ?>
                    <th>ID</th>
                <?php endif; ?>
                <th>Name</th>
                <th>Member Since</th>
                <?php if (hasRank("senior_admin", "junior_admin")): ?>
                    <th>Wallet</th>
                <?php endif; ?>
                <th>Actions</th>
            </tr>
            <?php foreach ($hits as $hit): ?>
                <tr>
                    <?php if (hasRank("senior_admin", "junior_admin")): ?>
                        <td>
                            <?php echo $hit["player_id"]; ?>
                        </td>
                    <?php endif; ?>
                    <td>
                        <div <?php echo userCSSColor($hit["player_name"]); ?>><?php echo $hit["player_name"]; ?></div>
                    </td>
                    <td>
                        <?php echo $hit["player_created"]; ?>
                    </td>
                    <?php if (hasRank("senior_admin", "junior_admin")): ?>
                        <td>
                            <?php echo $hit["player_wallet"]; ?> tregs
                        </td>
                    <?php endif; ?>
                    <td>
                        <?php if (hasRank("senior_admin", "junior_admin", "guardian") || $hit["player_id"] == $_SESSION["id"]): ?>
                            &raquo; <a href="/index.php/player/stats?id=<?php echo $hit["player_id"]; ?>">Stats</a><br />
                        <?php endif; ?>
                        <?php if (hasRank("senior_admin", "junior_admin", "guardian", "coder")): ?>
                            &raquo; <a href="/index.php/player/orelog?id=<?php echo $hit["player_id"]; ?>">Orelog</a><br />
                            &raquo; <a href="/index.php/player/report?id=<?php echo $hit["player_id"]; ?>">Reports</a><br />
                        <?php endif; ?>
                        <?php if (hasRank("senior_admin")): ?>
                            &raquo; <a href="/index.php/player/perm?id=<?php echo $hit["player_id"]; ?>">Permissions</a><br />
                        <?php endif; ?>
                        <?php if (hasRank("senior_admin", "junior_admin") || $hit["player_id"] == $_SESSION["id"]): ?>
                            &raquo; <a href="/index.php/player/zones?id=<?php echo $hit["player_id"]; ?>">Zones and Lots</a><br />
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>

    <?php endif; ?>
</div>
<?php endif; ?>