<div class="col75">

    <table class="info">
        <tr>
            <th colspan=3 class="infoHeader">Zones</th>
        </tr>
        <tr>
            <th width=100%>Zone</th>
            <th>Rank</th>
            <th>World</th>
        </tr>
        <?php
        foreach($zones as $zone) {
            echo "<tr><td><a href=\"zone_info.php?id=" . $zone['zone_id'] . "\">" . $zone['zone_name'] . "</a></td><td>" . $zone['user_perm'] . "</td><td>" . $zone['zone_world'] . "</td></tr>\n";
        }
        ?>
    </table>

    <table class="info">
        <tr>
            <th colspan=3 class="infoHeader">Lots</th>
        </tr>
        <tr>
            <th width=100%>Lot Name</th>
            <th>Zone</th>
            <th>World</th>
        </tr>
        <?php
        foreach($lots as $lot) {
            echo "<tr><td>" . $lot['lot_name'] . "</td><td><a href=\"zone_info.php?id=" . $lot['zone_id'] . "\">" . $lot['zone_name'] . "</a></td><td>" . $lot['zone_world'] . "</td></tr>\n";
        }
        ?>
    </table>

</div>

<div class="col25">

    <?php require_once 'player_menu.phtml'; ?>

</div>

<div class="col_clear">&nbsp;</div>
