<div class="col75">

    <h3 class="infoHeader">Logins</h3>
    <table class="info">
        <tr>
            <th>Timestamp</th>
            <th>Action</th>
            <th>IP</th>
            <th>Country</th>
            <th>City</th>
            <th>Duration</th>
        </tr>
        <?php 
        $last = null;
        $total = 0;
        $loginCount = 0;
        foreach ($logins as $i => $row):
            $duration = "";
            if ($row["login_action"] == "login") {
                $last = $row;
                $loginCount++;
            }
            else if ($row["login_action"] == "logout") {
                if ($last != null) {
                    $dur = $row["login_timestamp"] - $last["login_timestamp"];
                    $total += $dur;
                    $min = $dur / 60;
                    $sec = $dur % 60;
                    $duration = sprintf("%02d:%02d", $min, $sec);
                } else {
                    $duration = "N/A";
                }
            }
            if ($i < count($logins)-10) {
                continue;
            }
            ?>
            <tr>
                <td><?php echo date("Y-m-d H:i:s", $row["login_timestamp"]); ?></td>
                <td><?php echo ucfirst($row["login_action"]); ?></td>
                <td><?php echo $row["login_ip"]; ?></td>
                <td><?php echo $row["login_country"]; ?></td>
                <td><?php echo $row["login_city"]; ?></td>
                <td><?php echo $duration; ?></td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>
                <div>
                    <span style="font-weight: bold;">Total time:</span>
                    <?php
                    $hours = $total / 3600;
                    $min = ($total % 3600) / 60;
                    $sec = $total % 60;
                    printf("%02d:%02d:%02d", $hours, $min, $sec);
                    ?>
                </div>
                <div>
                    <span style="font-weight: bold;">Total logins:</span>
                    <?php printf("%d", $loginCount); ?>
                </div>
            </td>
        </tr>
    </table>


    <table class="info">
        <tr>
            <th colspan="4" class="infoHeader">Transactions</th>
        </tr>
        <tr>
            <th>Sender</th>
            <th>Receiver</th>
            <th>Timestamp</th>
            <th>Amount</th>
        </tr>
        <?php 
        foreach ($transactions as $row): ?>
            <tr>
                <td>
                    <?php 
                    if ($row["sender_id"] == $player["player_id"]) {
                        echo $player["player_name"]; 
                    } else {
                        echo $row["player_name"]; 
                    }
                    ?>
                </td>
                <td>
                    <?php 
                    if ($row["recipient_id"] == $player["player_id"]) {
                        echo $player["player_name"]; 
                    } else {
                        echo $row["player_name"]; 
                    }
                    ?>
                </td>
                <td><?php echo date("Y-m-d H:i:s", $row["transaction_timestamp"]); ?></td>
                <td><?php echo $row["transaction_amount"]; ?></td>
            </tr>
        <?php endforeach; ?>
    </table>

</div>
<div class="col25">
    <?php require_once 'player_menu.phtml'; ?>

    <br />

    <h3 class="infoHeader">Aliases</h3>
    <table class="info">
        <tr>
            <td>
                <?php foreach($aliases as $alias): ?>
                <a <?php echo userCSSColor($alias['player_name']); ?> href="/index.php/player/search?q=<?php echo $alias['player_name']; ?>"><?php echo $alias['player_name']; ?></a><br>
                <?php endforeach; ?>
            </td>
        </tr>
    </table>

</div>

<div class="col_clear">&nbsp;</div>

<table class="info">
    <tr>
        <th colspan="9" class="infoHeader">Inventory</th>
    </tr>

    <?php for ($x = 0; $x < 4; $x++): ?>
    <tr>
        <?php for ($y = 0; $y < 9; $y++): ?>
            <td style="width: 11%; height: 75px; border: 1px solid #000; text-align: center; font-size: 10px;">
                <?php
                if (array_key_exists($x*9+$y, $slots)) {
                    $slot = $slots[$x*9+$y];
                    $item = $slot["item_material"];
                    if ($item < 133) {
                        echo '<div><img src="/img/blocks/' . $item . '.png" width="50" height="50" /></div>';
                    } else {
                        echo '<div style="height: 50px;">' . 
                            implode(" ", array_map("ucfirst", array_map("strtolower", explode("_", $items[$item])))) . '</div>';
                    }
                    echo '<div>' . $slot["item_count"] . '</div>';
                } else {
                    echo "&nbsp;";
                }
                ?>
            </td>
        <?php endfor; ?>
    </tr>
    <?php endfor; ?>
</table>
