<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Re-Authenticate Yourself</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="/player/reset/keyword?id=<?php echo $subject["player_id"]; ?>" role="form">
                    <div class="form-group">
                      <i>Because you are removing two-factor authentication from a player, you must re-authenticate yourself.</i><br>
                      <b>If your password is incorrect, you will be signed out.</b>
                      <hr>
                      <label for="duration">Password</label>
                      <input type="password" class="form-control" id="password" name="password" />
                    </div>
                    <div class="form-group">
                      <label for="duration">Username of player being reset</label>
                      <input type="text" class="form-control" id="subjcet" name="subject" />
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="remove" name="remove"> Yes, I want to remove two-factor authentication from <?php echo $subject['player_name']; ?>
                        </label>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'player_menu.phtml'; ?>
    </div>
</div>
