<div class="col75">
<h3 class="infoHeader">Recent reports</h3>
<table style="width: 100%; border-spacing: 0;">
    <?php foreach ($reports as $i => $report): 
        $color = "#fff";
        if ($report["report_action"] == "ban") {
            $color = $i % 2 == 0 ? "#dfbbbb" : "#dfbbbb";
        }
        else if ($report["report_action"] == "softwarn" ||
                 $report["report_action"] == "hardwarn") {
            $color = $i % 2 == 0 ? "#bbbbd5" : "#bbbbdf";
        }
        else if ($report["report_action"] == "kick") {
            $color = $i % 2 == 0 ? "#bbd5d5" : "#bbdfdf";
        }
        else if ($report["report_action"] == "comment") {
            $color = $i % 2 == 0 ? "#d5d5d5" : "#dfdfdf";
        }
        ?>
        <tr style="background-color: <?php echo $color; ?>;">
            <td>
                <div style="margin: 5px; padding: 10px;">
                    <div style="text-align: center;">
                        <a href="/index.php/player/search?q=<?php echo $report["subject"]; ?>" <?php echo userCSSColor($report["subject_id"]); ?>><?php echo $report["subject"]; ?></a>
                    </div>
                    <div style="text-align: center; text-transform: uppercase; font-weight: bold; font-size: 15px; padding: 20px; color: #777;">
                        <?php echo ucfirst($report["report_action"]); ?>
                    </div>
                    <?php if ($report["report_validuntil"]): ?>
                        <div style="text-align: center;">
                            <?php echo "Until " . date("Y-m-d", $report["report_validuntil"]); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </td>
            <td>
                <div style="font-size: 1.2em; padding-top: 10px;">
                    <a href="/index.php/player/search?q=<?php echo $report["issuer"]; ?>" <?php echo userCSSColor($report["issuer_id"]); ?>><?php echo $report["issuer"]; ?>:</a>
                </div>
                <div style="font-size: 1.2em; padding: 20px;">
                    <p>
                    <?php
                    $msg = $report["report_message"];
                    $len = 500;
                    if (strlen($msg) > $len) {
                        $msg = substr($msg, 0, $len) . "...";
                    }
                    echo nl2br($msg);
                    ?>
                    </p>

                    <p>
                        <a href="/index.php/player/report?id=<?php echo $report["subject_id"]; ?>">View full report</a>
                    </p>
                </div>
                <div style="text-align: right;">
                    <?php echo niceTime($report["report_timestamp"]); ?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
</div>

<div class="col25">
    <?php require_once 'logs_menu.phtml'; ?>
</div>

<div class="col_clear">&nbsp;</div>
