<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <table class="table table-striped table-hover">
                <cols>
                    <col style="width: 150px;" />
                    <col style="width: 150px;" />
                    <col style="width: 75px;" />
                    <col style="width: 125px;" />
                    <col style="width: 125px;" />
                </cols>
                <tr>
                    <th>Issuer</th>
                    <th>Subject</th>
                    <th>Action</th>
                    <th>Timestamp</th>
                    <th>Valid Until</th>
                </tr>
                <?php foreach ($reports as $report): ?>
                    <tr>
                        <td style="font-style: italic;"><?php echo $report["issuer"]; ?></td>
                        <td style="font-style: italic;">
                            <a href="/index.php/player/report?id=<?php echo $report["subject_id"]; ?>"><?php echo $report["subject"]; ?></a>
                        </td>
                        <td style="font-style: italic;"><?php echo ucfirst($report["report_action"]); ?></td>
                        <td style="font-style: italic;"><?php echo date("Y-m-d H:i:s", $report["report_timestamp"]); ?></td>
                        <td style="font-style: italic;">
                            <?php
                            if ($report["report_validuntil"]) {
                                echo date("Y-m-d H:i:s", $report["report_validuntil"]);
                            } else {
                                echo "N/A";
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px dotted #fff;" colspan="5">
                            <?php
                            $msg = $report["report_message"];
                            $len = 500;
                            if (strlen($msg) > $len) {
                                $msg = substr($msg, 0, $len) . "...";
                            }
                            echo nl2br($msg);
                            ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'logs_menu.phtml'; ?>
    </div>
</div>
