<div class="col75">
    <h3 class="infoHeader">User quicksearch</h3>

    <form method="get" action="/index.php/player/search">
        <div class="field">
            <label for="player_search">User</label>
            <div class="element">
                <input type="text" name="q" id="player_search" />
            </div>
            <div class="end">&nbsp;</div>
        </div>

        <div class="button">
            <button type="submit">Search</button>
        </div>
    </form>

    <h3 class="infoHeader">Zone quicksearch</h3>

    <form method="get" action="/index.php/zone/search">
        <div class="field">
            <label for="zone_search">Zone</label>
            <div class="element">
                <input type="text" name="q" id="zone_search" />
            </div>
            <div class="end">&nbsp;</div>
        </div>

        <div class="button">
            <button type="submit">Search</button>
        </div>
    </form>

    <h3 class="infoHeader">Stats</h3>
    <div id="logins_chart" style="width: 100%; height: 400px;"></div>
    <div id="hour_chart" style="width: 100%; height: 400px;"></div>
    <div id="geo_chart" style="width: 100%; height: 400px;"></div>
    <div id="orelog_chart" style="width: 100%; height: 400px;"></div>
</div>

<div class="col25">
    <h3 class="actionsHeader"><?php echo count($players); ?> Online Players</h3>
    <ul class="actions">
    <?php foreach ($players as $player): ?>
        <li>
            <a <?php echo userCSSColor($player["id"]); ?> 
               href="/index.php/player/search?q=<?php echo $player["name"]; ?>">
               <?php echo $player["name"]; ?>
               [<a href="#" onclick="kickPlayer(<?php echo $player["id"]; ?>)">Kick</a>]
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>

<div class="col_clear">&nbsp;</div>
