<?php require_once 'index_news.phtml'; ?>

<div class="col25">
    <h3 class="infoHeader">User quicksearch</h3>

    <form method="get" action="/index.php/player/search" class="thin">
        <div class="field">
            <label for="player_search">User</label>
            <div class="element">
                <input type="text" name="q" id="player_search" />
            </div>
            <div class="end">&nbsp;</div>
        </div>

        <div class="button">
            <button type="submit">Search</button>
        </div>
    </form>

    <?php if (hasRank("junior_admin", "senior_admin")): ?>
    <h3 class="infoHeader">Zone quicksearch</h3>

    <form method="get" action="/index.php/zone/search" class="thin">
        <div class="field">
            <label for="zone_search">Zone</label>
            <div class="element">
                <input type="text" name="q" id="zone_search" />
            </div>
            <div class="end">&nbsp;</div>
        </div>

        <div class="button">
            <button type="submit">Search</button>
        </div>
    </form>
    <?php endif; ?>

    <?php if (count($players) > 0): ?>
    <h3 class="actionsHeader"><?php echo count($players); ?> Players Online</h3>
    <ul class="actions">
    <?php foreach ($players as $player): ?>
        <li>
            <a <?php echo userCSSColor($player["id"]); ?> 
               href="/index.php/player/search?q=<?php echo $player["name"]; ?>">
               <?php echo $player["name"]; ?>
               <?php if (hasRank("guardian", "builder", "coder", "junior_admin", "senior_admin")): ?>
               [<a href="#" onclick="kickPlayer(<?php echo $player["id"]; ?>)">Kick</a>]
               <?php endif; ?>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>

<div class="col_clear">&nbsp;</div>
