<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Stats</h3>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="/index.php/stats">Overview</a></li>
        <li class="list-group-item"><a href="/index.php/stats/playtime">Playtime</a></li>
        <li class="list-group-item"><a href="/index.php/stats/warps">Warps</a></li>
        <li class="list-group-item"><a href="/index.php/stats/mentors">Mentors</a></li>
        <li class="list-group-item"><a href="/index.php/stats/newplayers">New Players</a></li>
        <li class="list-group-item"><a href="/index.php/stats/fishyblocks">Fishy blocks</a></li>
    </ul>
</div>