<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Most students mentored</h3>
            </div>
            <table class="table table-striped table-hover">
                <cols>
                    <col />
                    <col style="width: 150px;" />
                </cols>
                <tr>
                    <th>Mentor</th>
                    <th>Students</th>
                </tr>
                <?php foreach ($mentors as $mentor): ?>
                    <tr>
                        <td>
                            <a <?php echo userCSSColor($mentor["mentor_id"]); ?>" href="/player/orelog?id=<?php echo $player["player_id"]; ?>"> <?php echo $mentor["player_name"]; ?></a>
                        </td>
                        <td style="text-align: center;"><?php echo $mentor["c"]; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'stats_menu.phtml'; ?>
    </div>
</div>
