    <h3 class="actionsHeader">Stats</h3>

    <ul class="actions">
        <li><a href="/index.php/stats">Overview</a></li>
        <li><a href="/index.php/stats/playtime">Playtime</a></li>
        <li><a href="/index.php/stats/warps">Warps</a></li>
        <li><a href="/index.php/stats/mentors">Mentors</a></li>
        <li><a href="/index.php/stats/newplayers">New Players</a></li>
        <li><a href="/index.php/stats/fishyblocks">Fishy blocks</a></li>
    </ul>
