<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Traffic</h3>
            </div>
            <div class="panel-body">
                <div id="logins_chart" style="width: 100%; height: 400px;"></div>
                <div id="unique_chart" style="width: 100%; height: 400px;"></div>
                <div id="online_chart" style="width: 100%; height: 400px;"></div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sources</h3>
            </div>
            <div class="panel-body">
                <div id="geo_chart" style="width: 100%; height: 400px;"></div>
            </div>
        </div>

        <?php if (array_key_exists("online", $_SESSION) && hasRank("guardian", "coder", "builder", "junior_admin", "senior_admin")): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Gameplay</h3>
            </div>
            <div class="panel-body">
                <div id="orelog_chart" style="width: 100%; height: 400px;"></div>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <div class="col-md-4">
        <?php require_once 'stats_menu.phtml'; ?>
    </div>
</div>
