<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default table-responsive">
            <div class="panel-heading">
                <h3 class="panel-title">Fishy Blocks</h3>
            </div>
            <table class="table table-striped table-hover">
                <cols>
                    <col />
                    <col />
                    <col />
                    <col />
                </cols>
                <tr>
                    <th>Player</th>
                    <th>Blocks</th>
                    <th>Items Sold</th>
                    <th>Total Cost</th>
                </tr>
                <?php foreach ($fishyblocks as $block): ?>
                    <tr>
                        <td>
                            <a <?php echo userCSSColor($block["player_id"]); ?>" href="/index.php/player/search?q=<?php echo $block["player_name"]; ?>"> <?php echo $block["player_name"]; ?></a>
                        </td>
                        <td style="text-align: center;"><?php echo $block["blocks"]; ?></td>
                        <td style="text-align: center;"><?php echo $block["sold"]; ?></td>
                        <td style="text-align: center;"><?php echo $block["cost"]; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        <?php require_once 'stats_menu.phtml'; ?>
    </div>
</div>