<div class="col75">
    <h3 class="infoHeader">Traffic</h3>
    <div id="logins_chart" style="width: 100%; height: 400px;"></div>
    <div id="unique_chart" style="width: 100%; height: 400px;"></div>
    <div id="online_chart" style="width: 100%; height: 400px;"></div>

    <p />

    <h3 class="infoHeader">Sources</h3>
    <div id="geo_chart" style="width: 100%; height: 400px;"></div>

    <p />

    <?php if (array_key_exists("online", $_SESSION) && hasRank("guardian", "coder", "builder", "junior_admin", "senior_admin")): ?>
    <h3 class="infoHeader">Gameplay</h3>
    <div id="orelog_chart" style="width: 100%; height: 400px;"></div>
    <?php endif; ?>
</div>

<div class="col25">
    <h3 class="actionsHeader">Stats</h3>

    <ul class="actions">
        <li><a href="/index.php/stats">Overview</a></li>
        <li><a href="/index.php/stats/playtime">Playtime</a></li>
        <li><a href="/index.php/stats/warps">Warps</a></li>
    </ul>
</div>

<div class="col_clear">&nbsp;</div>

