<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Stats</h3>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="/stats">Overview</a></li>
        <li class="list-group-item"><a href="/stats/playtime">Playtime</a></li>
        <li class="list-group-item"><a href="/stats/warps">Warps</a></li>
        <li class="list-group-item"><a href="/stats/mentors">Mentors</a></li>
        <li class="list-group-item"><a href="/stats/newplayers">New Players</a></li>
        <li class="list-group-item"><a href="/stats/fishyblocks">Fishy blocks</a></li>
    </ul>
</div>