<div class="col75">
    <h3 class="infoHeader">Traffic</h3>
    <div id="logins_chart" style="width: 100%; height: 400px;"></div>
    <div id="hour_chart" style="width: 100%; height: 400px;"></div>

    <p />

    <h3 class="infoHeader">Sources</h3>
    <div id="geo_chart" style="width: 100%; height: 400px;"></div>

    <?php if (array_key_exists("online", $_SESSION) && hasRank("guardian", "coder", "builder", "junior_admin", "senior_admin")): ?>
    <h3 class="infoHeader">Gameplay</h3>
    <div id="orelog_chart" style="width: 100%; height: 400px;"></div>
    <?php endif; ?>
</div>

<div class="col_clear">&nbsp;</div>

