<div class="col50">

    <table class="info">
        <tr>
            <th colspan=2 class="infoHeader">Info</th>
        </tr>
        <tr>
            <th width=50%>Attribute</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>World</td>
            <td><?php echo $zone["zone_world"]; ?></td>
        </tr>
        <tr>
            <td>Coordinates</td>
            <td>
            <?php foreach ($rects as $rect): ?>
                <?php echo "(".($rect['rect_x1'] ? $rect['rect_x1'] : 'NULL').",".($rect['rect_y1'] ? $rect['rect_y1'] : 'NULL').") - (".($rect['rect_x2'] ? $rect['rect_x2'] : 'NULL').",".($rect['rect_y2'] ? $rect['rect_y2'] : 'NULL').")"; ?><br />
            <?php endforeach; ?>
            </td>
        </tr>
        <tr>
            <td>Main Owner</td>
            <td><?php echo $zone["zone_owner"] ? "<a " . userCSSColor($zone["zone_owner"]) . "href=\"/index.php/player/search?q=" . $zone["zone_owner"] . "\">" . $zone["zone_owner"] . "</a>" : 'NULL'; ?></td>
        </tr>
        <tr>
            <td colspan=2>&nbsp;</td>
        </tr>
        <tr>
            <td>Enter Default</td>
            <td><?php echo $zone["zone_enterdefault"] ? "yes" : "no"; ?></td>
        </tr>
        <tr>
            <td>Place Blocks Default</td>
            <td><?php echo $zone["zone_placedefault"] ? "yes" : "no"; ?></td>
        </tr>
        <tr>
            <td>Destroy Blocks Default</td>
            <td><?php echo $zone["zone_destroydefault"] ? "yes" : "no"; ?></td>
        </tr>
        <tr>
            <td>PVP</td>
            <td><?php echo $zone["zone_pvp"] ? "yes" : "no"; ?></td>
        </tr>
        <tr>
            <td>Hostiles</td>
            <td><?php echo $zone["zone_hostiles"] ? "yes" : "no"; ?></td>
        </tr>
        <tr>
            <td>Enter Message</td>
            <td><?php echo $zone["zone_entermessage"]; ?></td>
        </tr>
        <tr>
            <td>Exit Message</td>
            <td><?php echo $zone["zone_exitmessage"]; ?></td>
        </tr>
        <tr>
            <td>Texture</td>
            <td><?php echo $zone["zone_texture"]; ?></td>
        </tr>

    </table>

    <table class="info">
        <tr>
            <th colspan=3 class="infoHeader">Members</th>
        </tr>
        <tr>
            <!-- <th>ID</th> -->
            <th width=100%>Name</th>
            <th>Rank</th>
            <th>Action</th>
        </tr>
        <?php 
        foreach ($users as $user): ?>
            <tr>
                <!-- <td><?php echo $user["player_id"]; ?></td> -->
                <td>
                <?php 
                echo "<a " . userCSSColor($user["player_id"]) . " href=\"/index.php/player/search?q=" . $user["player_name"] . "\">" . $user["player_name"] . "</a></td>\n";
                ?>
                <td><?php echo $user["user_perm"]; ?></td>
                <td></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<div class="col50">
    <table class="info">
        <cols>
            <col />
            <col style="width: 50px;" />
        </cols>
        <tr>
            <th colspan="2" class="infoHeader">Warps</th>
        </tr>
        <tr>
            <th>Name</th>
            <th>(x,y,z)</th>
        </tr>
        <?php foreach($warps as $warp): ?>
            <tr>
                <td><?php echo $warp['name']; ?></td>
                <td>(<?php printf("%d, %d, %d", $warp['x'], $warp['y'], $warp['z']); ?>)</td>
            </tr>
        <?php endforeach; ?>
    </table>

    <table class="info">
        <tr>
            <th colspan=2 class="infoHeader">Lots</th>
        </tr>
        <tr>
            <th width=100%>Name</th>
            <th>Owners</th>
        </tr>
        <?php foreach ($lots as $lot): ?>
        <tr>
            <td> <?php echo $lot["lot_name"]; ?></td>
            <td>
            <?php foreach($lot["users"] as $lVal): ?>
                <a <?php echo userCSSColor($lVal["player_id"]); ?>" 
                   href="/index.php/player/search?q=<?php echo $lVal["player_name"]; ?>">
                   <?php echo $lVal["player_name"]; ?></a><br>
            <?php endforeach; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<div class="col_clear">&nbsp;</div>
