<div class="panel panel-danger">
    <div class="panel-body">
        <form role="form" method="get" action="/zone/search">
            <div class="form-group">
                <label for="zone_search">Zone</label>
                <input type="text" class="form-control" id="zone_search" name="q" value="<?php echo htmlspecialchars($q); ?>" />
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>
    </div>
</div>

<div class="panel panel-primary table-responsive">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo count($hits); ?> results for "<?php echo htmlspecialchars($q); ?>"</h3>
    </div>

    <?php if ($hits): ?>
        <table style="width: 100%;" class="table table-striped table-hover">
            <cols>
                <col style="width: 50px;" />
                <col />
                <col style="width: 200px;" />
                <col style="width: 200px;" />
            </cols>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>World</th>
                <th>Actions</th>
            </tr>
            <?php foreach ($hits as $hit): ?>
                <tr>
                    <td>
                        <?php echo $hit["zone_id"]; ?>
                    </td>
                    <td>
                        <?php echo $hit["zone_name"]; ?>
                    </td>
                    <td>
                        <?php echo $hit["zone_world"]; ?>
                    </td>
                    <td>
                        &raquo; <a href="/zone/profile?id=<?php echo $hit["zone_id"]; ?>">Profile</a><br />
                        <?php if (hasRank("junior_admin", "senior_admin")): ?>
                            &raquo; <a href="/zone/info?id=<?php echo $hit["zone_id"]; ?>">Info</a><br />
                            &raquo; <a href="/zone/edit?id=<?php echo $hit["zone_id"]; ?>">Edit</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <div class="panel-body">
            <div class="alert alert-danger">No hits were found!</div>
        </div>
    <?php endif; ?>
</div>

